### ISSUE TITLE
Loading the json string directly without the need of a file?

### ISSUE THREAD

**Issue by oxio2** [realBoubli/MonoGame-LDtk-Importer#3]
Is it possible to add a constructor that loads the LDtkProject project using a string instead of a filePath?

**Comment by boubl** [comment]
Yeah, that shouldn't be a problem, I'll add that !

**Comment by boubl** [comment]
Hum, no, I have a problem... LDtk store the file paths for the tilesets and externals levels, and all the others externals resources as  **relative paths**, so without the original file path, I can't load externals resources. The only way I could fix that is to ask DeepKnight to add an option in order to store file path as full ones.
